#global:
#  scrape_interval: 15s

#scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['0.0.0.0:9090']

#  - job_name: 'docker_cv'
#      static_configs:
#      - targets: ['0.0.0.0:5000']

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.0.174:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.0.174:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['192.168.0.174:3000']

  - job_name: 'my_docker_cv_container1'
    static_configs:
      - targets: ['192.168.0.174:5000']

  - job_name: 'my_docker_cv_container2'
    static_configs:
      - targets: ['192.168.0.174:5001']

  - job_name: 'my_docker_cv_container3'
    static_configs:
      - targets: ['192.168.0.174:5002']

  - job_name: 'my_docker_cv_container_test_ip_fix'
    static_configs:
      - targets: ['192.168.0.174:5003']
